# Site settings
title: Eva-Christin Ernst
description: "An informal vita about Eva-Christin Ernst."
url: "http://eva-ernst.me"
author:
  name: "Eva-Christin Ernst"
  email: "hello@eva-ernst.me"
  url: "http://eva-ernst.me"

# Build settings
baseurl: '' # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site

permalink: /blog/:title
paginate: 8
paginate_path: /blog/page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock

# Options
custom_header: false
custom_nav_footer: false
reverse: false
