# Site settings
title: Eva-Christin Ernst Blog About Travel and WomenInTech
description: "An informal vita and a blog about and by Eva-Christin Ernst."
url: "http://eva-ernst.me"

twitter:
  username: EvaCErnst

# Build settings
baseurl: '' # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site

permalink: /blog/:title/
paginate: 8
paginate_path: /blog/page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - license.md
  - README.md
  - .gitignore

# Options
custom_header: false
custom_nav_footer: false
reverse: false
