name: jekyll build and deploy artifact with rsync

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Build the site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: "-avzr --prune-empty-dirs --delete"
          options: "--exclude *.scss"
          ssh_options: ""
          src: "_site/"
          dest: "eva231@albiorix.uberspace.de:/home/eva231/html"
