name: jekyll build and deploy artifact with rsync

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Build the site
        env:
          JEKYLL_ENV: production
        run: |
          bundle config path vendor/bundle
          bundle config --global frozen 1
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build
      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        with:
          flags: "-avzr --prune-empty-dirs --delete"
          options: "--exclude *.scss"
          ssh_options: ""
          src: "_site/"
          dest: "eva256@schedar.uberspace.de:/home/eva256/www/eva-ernst.me"
